### ISSUE TITLE
Missing items in core.py from BAG framework to run bpg setup_workspace  

### ISSUE THREAD

**Issue by fabio17** [BerkeleyPhotonicsGenerator/BPG#169]
Hi, I'm trying to run bpg setup_workspace but I get the following error: 
File "/home/fpavanel/bpg_work/BPG/BPG/photonic_core.py", line 14, in <module>
    from bag.core import BagProject, create_tech_info, _parse_yaml_file, _import_class_from_str
ImportError: cannot import name '_parse_yaml_file' from 'bag.core' (/home/fpavanel/bpg_work/BPG/BAG/BAG_framework/bag/core.py)

I've installed the master version of BAG framework, however it seems it's not the right version as it's missing some functions.  Any idea?

**Comment by pvnbhargava** [comment]
Hi Fabio, thanks for the feedback, and sorry it took so long to get around to fixing things. This error is popping up because one of our dependencies, Berkeley Analog Generator, made a backward incompatible change. I've now fixed this issue and pushed to master.
